spring.application.name=back-end

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cms?useSSL=false
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/prescriptions

# Actuator
management.endpoint.health.show-details=always
management.health.db.enabled=true

# API
api.path=/

# JWT
jwt.secret=$!@#$^%$$$%####$DDCPN0234FCFDPD8670M

# Static resources
spring.web.resources.static-locations=classpath:/static/

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
